version: "3.9"
services:
  cassandra:
    image: "mcfongtw/rpi-cassandra:3.11"
  elastic:
    build:
        dockerfile: Dockerfile
        context: ./elastic
    image: boodskapiot/elastic-rpi
  platform:
    build:
        dockerfile: Dockerfile
        context: ./platform
    image: boodskapiot/platform-rpi
    depends_on:
      - cassandra
      - elastic
  ui:
    build:
        dockerfile: Dockerfile
        context: ./ui
    image: boodskapiot/ui-rpi
    ports:
      - "4201:4201"
    depends_on:
      - platform
  dashboard:
    build:
        dockerfile: Dockerfile
        context: ./dashboard
    image: boodskapiot/dashboard-rpi
    ports:
      - "10000:10000"
    depends_on:
      - ui
  gateway:
    build:
        dockerfile: Dockerfile
        context: ./gateway
    image: boodskapiot/gateway-rpi
    ports:
      - "80:80"
    depends_on:
      - dashboard
